name: Build SOPSoft ERP APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet y dependencias
        run: |
          pip install flet --upgrade

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          # Usamos la versión que el log de error solicitó
          flutter-version: '3.41.4' 
          channel: 'stable'

      - name: Compilar APK con Flet
        run: |
          # El comando 'yes' envía automáticamente la letra 'y' a cualquier pregunta
          yes | flet build apk --project "SOPSoft ERP" --org com.yohander.sopsoft

      - name: Subir APK como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: SOPSoft-Release-APK
          path: build/apk/*.apk